### ISSUE TITLE
New login page components

### ISSUE THREAD

**Issue by vmcodes** [ObjectPress/object-press#15]
We should update the login page to not use the default AWS Authenticator login UI and switch to only [Base Web](https://baseweb.design/) components. I would like to handle the functionality related to AWS, but essentially we would need the following components to be created:
Login.tsx
Register.tsx
Verify.tsx
ForgotPassword.tsx
ChangePassword.tsx

**Comment by Deotyma** [comment]
Hello. I would like to be assigned to this issue.

**Comment by ObjectPress** [comment]
This issue appears to be resolved by switching back production hosting to AWS. I believe this is because Amplify is an AWS service, so using them to host the site reduces latency. I'll give it a couple days of testing before closing the issue.
