### ISSUE TITLE
Add form validation

### ISSUE THREAD

**Issue by vmcodes** [ObjectPress/object-press#6]
We should add form validation using [react-hooks-form](https://react-hook-form.com/). The idea would be to add this to all drawer components for creating blogs, posts, and profile info. This should be done using this [repo](https://github.com/react-hook-form/react-hook-form/blob/master/examples/V7/registerWithErrorMessages.tsx) as an example.

**Comment by urtadolg** [comment]
Hello. Can I be assigned to this ? I would like to know more details. Do you have discord?

**Comment by vmcodes** [comment]
@urtadolg assigned it to you. we do have a [slack](https://join.slack.com/t/object-press/shared_invite/zt-15dx55b3l-ApogR4eHsbA8RWK_es5cLw) group.
