### ISSUE TITLE
Add the NoResults component to the gallery search

### ISSUE THREAD

**Issue by ObjectPress** [ObjectPress/object-press#7]
I was thinking about possibly showing the NoResult.tsx component when the search results or blog sort features of the Gallery.tsx container have no images to display, instead of the place holder skeletons being displayed currently. We could add some new conditional rendering for showing the skeletons when first loading the page/clearing the results, but displaying the NoResults.tsx component when no results are actually found. As always, open to any suggestions.

**Comment by urtadolg** [comment]
can I be assigned to this?

**Comment by vmcodes** [comment]
@urtadolg sure thing, thanks!
